//HintName: CustomDateOnlyTypeConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using AltaSoft.DomainPrimitives;
using System;
using System.ComponentModel;
using System.Globalization;

namespace AltaSoft.DomainPrimitives.Converters;

/// <summary>
/// TypeConverter for <see cref = "CustomDateOnly"/>
/// </summary>
internal sealed class CustomDateOnlyTypeConverter : DateOnlyConverter
{
    /// <inheritdoc/>
    public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
    {
        if (value is string s)
        {
            try
            {
                return CustomDateOnly.Parse(s, culture);
            }
            catch (InvalidDomainValueException ex)
            {
                throw new FormatException("Cannot parse ", ex);
            }
        }

        return base.ConvertFrom(context, culture, value);
    }
}
