//HintName: CustomTimeSpanJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using AltaSoft.DomainPrimitives;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;

namespace AltaSoft.DomainPrimitives.Converters;

/// <summary>
/// JsonConverter for <see cref = "CustomTimeSpan"/>
/// </summary>
internal sealed class CustomTimeSpanJsonConverter : JsonConverter<CustomTimeSpan>
{
    /// <inheritdoc/>
    public override CustomTimeSpan Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
            throw new JsonException("Expected a string value to deserialize CustomTimeSpan");

        var str = reader.GetString() ?? throw new JsonException("Expected a non-null string value to deserialize CustomTimeSpan");
        try
        {
            return CustomTimeSpan.Parse(str, CultureInfo.InvariantCulture);
        }
        catch (InvalidDomainValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, CustomTimeSpan value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("hh\\:mm", CultureInfo.InvariantCulture));
    }

    /// <inheritdoc/>
    public override CustomTimeSpan ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
            throw new JsonException("Expected a string value to deserialize CustomTimeSpan");

        var str = reader.GetString() ?? throw new JsonException("Expected a non-null string value to deserialize CustomTimeSpan");
        try
        {
            return CustomTimeSpan.Parse(str, CultureInfo.InvariantCulture);
        }
        catch (InvalidDomainValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CustomTimeSpan value, JsonSerializerOptions options)
    {
        writer.WritePropertyName(value.ToString("hh\\:mm", CultureInfo.InvariantCulture));
    }
}
