//HintName: OpenApiHelper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable IDE0290 // Use primary constructor

using AltaSoft.DomainPrimitives;
using Microsoft.OpenApi;
using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Text.Json.Nodes;

[assembly: AltaSoft.DomainPrimitives.DomainPrimitiveAssemblyAttribute]
namespace generator_Test.Converters.Helpers;

/// <summary>
/// Helper class providing methods to configure OpenApiSchema mappings for DomainPrimitive types of generator_Test
/// </summary>
public static class OpenApiHelper
{
    /// <summary>
    /// Mapping of DomainPrimitive types to OpenApiSchema definitions.
    /// </summary>
    /// <remarks>
    /// The Dictionary contains mappings for the following types:
    /// <para>
    /// <see cref="ByteValue" />
    /// </para>
    /// </remarks>
    public static FrozenDictionary<Type, OpenApiSchema> Schemas = new Dictionary<Type, OpenApiSchema>()
    {
        {
            typeof(ByteValue),
            new OpenApiSchema
            {
                Type = JsonSchemaType.Integer,
                Format = "uint8",
                Title = "ByteValue"
            }
        }
    }.ToFrozenDictionary();
}
