//HintName: OpenApiHelper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using AltaSoft.DomainPrimitives;
using Microsoft.OpenApi;
using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Text.Json.Nodes;

[assembly: AltaSoft.DomainPrimitives.DomainPrimitiveAssemblyAttribute]
namespace generator_Test.Converters.Helpers;

/// <summary>
/// Helper class providing methods to configure OpenApiSchema mappings for DomainPrimitive types of generator_Test
/// </summary>
public static class OpenApiHelper
{
    /// <summary>
    /// Mapping of DomainPrimitive types to OpenApiSchema definitions.
    /// </summary>
    /// <remarks>
    /// The Dictionary contains mappings for the following types:
    /// <para>
    /// <see cref="CustomDateOnly" />
    /// </para>
    /// </remarks>
    public static FrozenDictionary<Type, OpenApiSchema> Schemas = new Dictionary<Type, OpenApiSchema>()
    {
        {
            typeof(CustomDateOnly),
            new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Format = "yyyyMMdd",
                Title = "CustomDateOnly"
            }
        }
    }.ToFrozenDictionary();
}
