//HintName: CustomDateOnlyJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable IDE0290 // Use primary constructor

using AltaSoft.DomainPrimitives;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;

namespace AltaSoft.DomainPrimitives.Converters;

/// <summary>
/// JsonConverter for <see cref = "CustomDateOnly"/>
/// </summary>
internal sealed class CustomDateOnlyJsonConverter : JsonConverter<CustomDateOnly>
{
    /// <inheritdoc/>
    public override CustomDateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
            throw new JsonException("Expected a string value to deserialize CustomDateOnly");

        var str = reader.GetString() ?? throw new JsonException("Expected a non-null string value to deserialize CustomDateOnly");
        try
        {
            return CustomDateOnly.Parse(str, CultureInfo.InvariantCulture);
        }
        catch (InvalidDomainValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, CustomDateOnly value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("yyyyMMdd", CultureInfo.InvariantCulture));
    }

    /// <inheritdoc/>
    public override CustomDateOnly ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
            throw new JsonException("Expected a string value to deserialize CustomDateOnly");

        var str = reader.GetString() ?? throw new JsonException("Expected a non-null string value to deserialize CustomDateOnly");
        try
        {
            return CustomDateOnly.Parse(str, CultureInfo.InvariantCulture);
        }
        catch (InvalidDomainValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CustomDateOnly value, JsonSerializerOptions options)
    {
        writer.WritePropertyName(value.ToString("yyyyMMdd", CultureInfo.InvariantCulture));
    }
}
