//HintName: DateOnlyValueJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using AltaSoft.DomainPrimitives;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;

namespace AltaSoft.DomainPrimitives.Converters;

/// <summary>
/// JsonConverter for <see cref = "DateOnlyValue"/>
/// </summary>
public sealed class DateOnlyValueJsonConverter : JsonConverter<DateOnlyValue>
{
    /// <inheritdoc/>
    public override DateOnlyValue Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.DateOnlyConverter.Read(ref reader, typeToConvert, options);
        }
        catch (InvalidDomainValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, DateOnlyValue value, JsonSerializerOptions options)
    {
        JsonInternalConverters.DateOnlyConverter.Write(writer, (DateOnly)value, options);
    }

    /// <inheritdoc/>
    public override DateOnlyValue ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.DateOnlyConverter.ReadAsPropertyName(ref reader, typeToConvert, options);
        }
        catch (InvalidDomainValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, DateOnlyValue value, JsonSerializerOptions options)
    {
        JsonInternalConverters.DateOnlyConverter.WriteAsPropertyName(writer, (DateOnly)value, options);
    }
}
