//HintName: OpenApiHelper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft DomainPrimitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

#if NET10_0_OR_GREATER
using Microsoft.OpenApi;
#else
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Any;
#endif
using AltaSoft.DomainPrimitives;
using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Text.Json.Nodes;

[assembly: AltaSoft.DomainPrimitives.DomainPrimitiveAssemblyAttribute]
namespace generator_Test.Converters.Helpers;

/// <summary>
/// Helper class providing methods to configure OpenApiSchema mappings for DomainPrimitive types of generator_Test
/// </summary>
public static class OpenApiHelper
{
    /// <summary>
    /// Mapping of DomainPrimitive types to OpenApiSchema definitions.
    /// </summary>
    /// <remarks>
    /// The Dictionary contains mappings for the following types:
    /// <para>
    /// <see cref="DateTimeOffsetValue" />
    /// </para>
    /// </remarks>

#if NET10_0_OR_GREATER
    public static FrozenDictionary<Type, OpenApiSchema> Schemas = new Dictionary<Type, OpenApiSchema>()
    {
        {
            typeof(DateTimeOffsetValue),
            new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Format = "date-time",
                Title = "DateTimeOffsetValue"
            }
        }
    }.ToFrozenDictionary();

#else
    public static FrozenDictionary<Type, OpenApiSchema> Schemas = new Dictionary<Type, OpenApiSchema>()
    {
        {
            typeof(DateTimeOffsetValue),
            new OpenApiSchema
            {
                Type = "string",
                Format = "date-time",
                Title = "DateTimeOffsetValue"
            }
        },

        {
            typeof(DateTimeOffsetValue?),
            new OpenApiSchema
            {
                Type = "string",
                Format = "date-time",
                Nullable = true,
                Title = "Nullable<DateTimeOffsetValue>"
            }
        }
    }.ToFrozenDictionary();
#endif
}
